# Generated by Django 5.0.1 on 2024-02-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habeshaE', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/media/Stuff-Best-Smartphone-Lead.webp', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
