# Generated by Django 5.0.1 on 2024-02-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habeshaE', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
