# Generated by Django 5.0.1 on 2024-02-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habeshaE', '0004_uploadedimage_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
