# Generated by Django 5.0.1 on 2024-02-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habeshaE', '0005_alter_uploadedimage_price'),
    ]

    operations = [
    ]
