# Generated by Django 5.0.1 on 2024-02-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habeshaE', '0006_auto_20240210_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Uncategorized', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
    ]
