# Generated by Django 5.0.1 on 2024-02-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habeshaE', '0008_alter_category_options_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
